name: First Workflow
on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 1
        env:
          MY_SECRET_VAR: ${{ secrets.MY_SECRET_VAR }}
        run: echo $MY_SECRET_VAR

  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Ship it
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'Ready for prod–ship it! ${{ env.MY_VAR }}'
        color: 'magenta'