name: First Workflow
on:
  workflow_dispatch:
  issues:
    types: [opened]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Job 1
        run: echo "This is job 1"

  job2:
    runs-on: ubuntu-latest
    steps:
    - name: Ship it
      uses: mscoutermarsh/cowsays-action@master
      with:
        text: 'Ready for prod–ship it!'
        color: 'magenta'