name: Delete Azure Resource Group

on:
  workflow_dispatch:
    inputs:
      appenv:
        type: choice
        description: Choose the target environment
        options:
          - dev
          - test
          - prod

jobs:
  destroy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    # Checkout code
    - uses: actions/checkout@main

    # Log into Azure
    - uses: azure/login@v2.1.1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        enable-AzPSSession: true

    # Destroy Resource Group
    - name: Azure ARM Deployment
      uses: azure/ARM@v1
      with:
        azcliversion: 2.0.72
        inlineScript: |
          az group delete --name ${{ secrets.AZURE_RG }} --yes --no-wait